# -*- coding: utf-8 -*-
"""Spam detector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17_FBGS2ajMCXcHirEz0uCuhwDI_vPQ3K
"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Dataset
messages = [
    "Win money now",
    "Claim your free prize",
    "Congratulations you won lottery",
    "Free mobile recharge",
    "Hello how are you",
    "Let's meet tomorrow",
    "Are you coming today",
    "Call me later",
    "Important account update",
    "Get free coupons now"
]

labels = [
    "spam",
    "spam",
    "spam",
    "spam",
    "ham",
    "ham",
    "ham",
    "ham",
    "ham",
    "spam"
]

# Convert text into numbers
cv = CountVectorizer()
X = cv.fit_transform(messages)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, labels, test_size=0.2, random_state=42
)

# Train model
model = MultinomialNB()
model.fit(X_train, y_train)

# Test accuracy
predictions = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, predictions))

# User input
user_message = input("Enter message: ")

# Transform input
user_data = cv.transform([user_message])

# Predict
result = model.predict(user_data)

print("Prediction:", result[0])